name: tiled_workspace
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"

workspace:
  - packages/tiled

dev_dependencies:
  melos: ^8.1.0

melos:
  repository: https://github.com/flame-engine/tiled.dart

  scripts:
    coverage:
      run: |
        dart run melos exec -- flutter test --coverage &&
        dart run melos exec -- genhtml coverage/lcov.info --output-directory=coverage/
      packageFilters:
        dirExists: test
      description: Generate coverage for the selected package.

    update-goldens:
      run: dart run melos exec -- flutter test --update-goldens
      packageFilters:
        dirExists: test
      description: Re-generate all golden test files
