name: tiled
version: 0.11.1
description: A Dart Tiled library. Parse your TMX files into useful representations. Compatible with Flame.
homepage: https://github.com/flame-engine/tiled.dart

environment:
  sdk: ">=3.11.0 <4.0.0"

resolution: workspace

dependencies:
  archive: ^4.0.2
  collection: ^1.16.0
  meta: ^1.7.0
  xml: ^7.0.0

dev_dependencies:
  dartdoc: ^9.0.0
  flame_lint: ^1.1.2
  test: ^1.24.8
